site_name: Keiner kennt Shoes
theme: readthedocs

pages:
- Home: "index.md"
- Schnelle Notizen: "dailynotes.md"

markdown_extensions:
- footnotes
- smarty:
    smart_quotes: False
- pymdownx.tasklist

site_dir: "/Applications/MAMP/htdocs/learningshoes"

extra_css: [css/user.css]

edit_uri: blob/master/docs

repo_url: "https://github.com/kantel/learningshoes"
